services:
  app:
    container_name: truck-simulator-dedicated-server
    image: truck-simulator-dedicated-server:latest
    build: .
    env_file: .env
    ports:
      - 27015:27015/tcp #Connection Dedicated Port
      - 27015:27015/udp #Connection Dedicated Port
      - 27016:27016/tcp #Query Dedicated Port
      - 27016:27016/udp #Query Dedicated Port
    volumes:
      - ./data:/data
      - ./cache:/cache